### ISSUE TITLE
Доработка страниц

### ISSUE THREAD

**Issue by AnastasiaKorol** [Milording/ls#2]
1. Все переходы на страницы должны быть частью страницы и хранится в методах GetPage, например. Чтобы вызывать MainPage.GetPage(), а не Driver.Navigate.GoToUrl("http://host")
2. Методы в страницах должны возвращать либо текущий PageObject либо новый, если в результате действий произошел переход между страницами.

**Comment by Milording** [comment]
[getPage methods](https://github.com/Milording/ls/commit/38656523e7328c8300c26934ade2a2dde2d5e64c)
не уверен, что понял правильно, но вроде так.
