### ISSUE TITLE
Использование SetUp и TearDown

### ISSUE THREAD

**Issue by AnastasiaKorol** [Milording/ls#4]
Вместо самописных методов SetUp и TearDown использовать специально придуманные для этого одноименные методы NUnit.

**Comment by Milording** [comment]
Изначально я использовал эти методы только для страницы с устным переводом, так как там требуется соблюдать порядок и не закрывать браузер после каждого теста, а никакого другого варианта, чтобы запустить общий SetUp для всех методов, я не нашел [(SO)](http://stackoverflow.com/questions/18413865/nunit-how-to-have-a-once-off-setup-method-for-all-tests)
после чего решил оставить для остальных, чтобы не нарушать структуру. Сейчас переписал для всех тестов, кроме устного перевода, там оставил только TearDown для логгинга.
[log to file and screenshot](https://github.com/Milording/ls/commit/33c886b49102e4d870363678269a366621ab7cfa)
